name: POC for Path based trigger

on:
    workflow_dispatch:
    push:
    #    paths:
    #        - 'src/**'
    #        - 'gradle/**'
jobs:
    trigger-poc:
        name: 'Path based Trigger POC'
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository to the GitHub Actions runner
              - name: 'Checkout'
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
              - name: Check for changes
                id: checkForChanges
                run: |
                    git diff --name-only ${{ github.event.after }} ${{ github.event.before }} > committedfiles.txt
                    filelist="./committedfiles.txt"
                    echo "File list"
                    cat committedfiles.txt
                    i=0
                    while IFS= read -r currentline
                    do
                      echo iteration$i,$(dirname ${currentline})
                      i=i+1
                    done < "$filelist" > folderlist.txt
                    echo "Folder list"
                    cat folderlist.txt
                    sort folderlist.txt | uniq -i > uniqfolderlist.txt
                    echo "After uniq"
                    jq -Rs '[ split("\n")[] | select(length > 0) | split(",") | {.[0]: .[1] ]' uniqfolderlist.txt
