name: POC for Path based trigger

on:
    workflow_dispatch:
    push:
        paths:
            - 'src/**'
jobs:
    trigger-poc:
        name: 'Path based Trigger POC'
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository to the GitHub Actions runner
              - name: 'Checkout'
                uses: actions/checkout@v2
              - name: Check the path
                run: |
                  echo ${{ github.event.repository.name }}
                  echo ${{ github.event.path }}
              - name: Dump GitHub context
                env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
                run: echo "$GITHUB_CONTEXT"
              - name: Dump job context
                env:
                  JOB_CONTEXT: ${{ toJson(job) }}
                run: echo "$JOB_CONTEXT"
              - name: Dump steps context
                env:
                  STEPS_CONTEXT: ${{ toJson(steps) }}
                run: echo "$STEPS_CONTEXT"
              - name: Dump runner context
                env:
                  RUNNER_CONTEXT: ${{ toJson(runner) }}
                run: echo "$RUNNER_CONTEXT"
              - name: Dump strategy context
                env:
                  STRATEGY_CONTEXT: ${{ toJson(strategy) }}
                run: echo "$STRATEGY_CONTEXT"
              - name: Dump matrix context
                env:
                  MATRIX_CONTEXT: ${{ toJson(matrix) }}
                run: echo "$MATRIX_CONTEXT"
