name: POC for Path based trigger

on:
    workflow_dispatch:
    push:
    #    paths:
    #        - 'src/**'
    #        - 'gradle/**'
jobs:
    trigger-poc:
        name: 'Path based Trigger POC'
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository to the GitHub Actions runner
              - name: 'Checkout'
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
              - name: Check for changes
                id: checkForChanges
                run: |
                    git diff --name-only ${{ github.event.after }} ${{ github.event.before }} > committedfiles.txt
                    filelist="./committedfiles.txt"
                    "File list"
                    cat committedfiles.txt
                    while IFS= read -r currentline
                    do
                      echo $(dirname ${currentline})
                    done < "$filelist" > folderlist.txt
                    "Folder list"
                    cat folderlist.txt
                    sort folderlist.txt | uniq -i
                    echo "After uniq"
                    cat folderlist.txt

              
