name: POC for Path based trigger

on:
    workflow_dispatch:
    push:
    #    paths:
    #        - 'src/**'
    #        - 'gradle/**'
jobs:
    trigger-poc:
        name: 'Path based Trigger POC'
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository to the GitHub Actions runner
              - name: 'Checkout'
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
              - name: (CI) Dependencies update check
                run: |
                    current_commit=`git log -n 1 --pretty=format:%H`
                    echo $current_commit
                    last_deps_mod_commit=`git log -n 1 --pretty=format:%H -- composer.json`
                    echo $last_deps_mod_commit
                    if [ $current_commit == $last_deps_mod_commit ]; then echo USE_LOCK=0 > ci.conf; else echo USE_LOCK=1 > ci.conf; fi
              - name: Check for changes
                id: checkForChanges
                run: |
                    git diff --name-only ${{ github.event.after }} ${{ github.event.before }}

              - name: Check the path
                env:
                  EVENT_CONTEXT: ${{ toJson(github.event) }}
                run: |
                  echo "Event"
                  git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
                  git diff --name-only ${{ github.event.before }} ${{ github.sha }}
                  #echo "github.event.path"
                  #echo ${{github.event_path}}
                  #echo "JSON CAT"
                  #cat "/home/runner/work/_temp/_github_workflow/event.json"
                  #echo "EVENT_CONTEXT"
                  #echo "$EVENT_CONTEXT"
              - name: Dump GitHub context
                env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
                run: echo "$GITHUB_CONTEXT"
              - name: Dump job context
                env:
                  JOB_CONTEXT: ${{ toJson(job) }}
                run: echo "$JOB_CONTEXT"
              - name: Dump steps context
                env:
                  STEPS_CONTEXT: ${{ toJson(steps) }}
                run: echo "$STEPS_CONTEXT"
              - name: Dump runner context
                env:
                  RUNNER_CONTEXT: ${{ toJson(runner) }}
                run: echo "$RUNNER_CONTEXT"
              - name: Dump strategy context
                env:
                  STRATEGY_CONTEXT: ${{ toJson(strategy) }}
                run: echo "$STRATEGY_CONTEXT"
              - name: Dump matrix context
                env:
                  MATRIX_CONTEXT: ${{ toJson(matrix) }}
                run: echo "$MATRIX_CONTEXT"
